### ISSUE TITLE
CPU and GPU versions have different results

### ISSUE THREAD

**Issue by zhuzhenxi** [wangzehui20/OTAM-Video-via-Temporal-Alignment#1]
Hi, I follow the Example Usage but an error occurred: 
`Profiling forward() + backward() times for batch_size=128, seq_len_a=17, seq_len_b=15, dims=2...
Traceback (most recent call last):
  File "softerdtw_padquery_update2_right.py", line 530, in <module>
    profile(128, 17, 15, 2, tol_backward=1e-6)
  File "softerdtw_padquery_update2_right.py", line 506, in profile
    assert torch.allclose(forward_cpu, forward_gpu.cpu())
AssertionError`
It seems that CPU and GPU versions have different results?

**Comment by wangzehui20** [comment]
Sry, I mainly focused on gpu-code when i reimplemented this. I update cpu-code just now, but also find this error occurs: CPU and GPU results are only slightly different in calculating backward prop. Maybe math library and numpy result in problems

**Comment by zhuzhenxi** [comment]
Thank you for your reply! I'm a little confused about update2_down and update2_right. Because of symmetry, if the input sequence of DTW is exchanged, is it equivalent to exchanging update2_down and update2_right? 
```
import torch
from softerdtw_padquery_update2_down import SoftDTW as SDTW_D
from softerdtw_padquery_update2_right import SoftDTW as SDTW_R

sdtw_d = SDTW_D(False, gamma=0.1, normalize=False)
sdtw_r = SDTW_R(False, gamma=0.1, normalize=False)

batch_size, seq_len_a, seq_len_b, dims = 1,8,8,2048

a_cpu = torch.rand((batch_size, seq_len_a, dims), requires_grad=True)
b_cpu = torch.rand((batch_size, seq_len_b, dims), requires_grad=True)

forward_d = sdtw_d(a_cpu,b_cpu) + sdtw_d(b_cpu,a_cpu)
print(forward_d)
forward_r = sdtw_r(a_cpu,b_cpu) + sdtw_r(b_cpu,a_cpu)
print(forward_r)
assert torch.allclose(forward_d, forward_r) #False
```
Suppose I have two time series a_cpu and b_cpu, I want to calculate their sdtw cumulative distance (OTAM averages the two alignment scores under two directions). Which of the following is correct?
```
sdtw_d(a_cpu,b_cpu) + sdtw_d(b_cpu,a_cpu)
sdtw_r(a_cpu,b_cpu) + sdtw_r(b_cpu,a_cpu)
sdtw_d(a_cpu,b_cpu) + sdtw_r(a_cpu,b_cpu)
sdtw_d(b_cpu,a_cpu) + sdtw_r(b_cpu,a_cpu)
```

**Comment by wangzehui20** [comment]
yes, it's symmetrical when you exchange two sequences. I used this code on video retrieval, so query video as prototype to match many other gallery videos which is significant for _down and _right two ways.
`sdtw_d(a_cpu,b_cpu)` and `sdtw_d(b_cpu,a_cpu)` maybe different because of default pad query videos.
`sdtw_d(a_cpu,b_cpu)` and `sdtw_r(a_cpu,b_cpu)` are different in principle but mostly they choose same path.
If you exchange the pad way, `sdtw_d(a_cpu,b_cpu)` and `sdtw_r(b_cpu,a_cpu)` are same.
